### ISSUE TITLE
MVCC_READ_CONFLICT ERROR

### ISSUE THREAD

**Issue by EurusLiao** [hyperledger-labs/pubsub-interop#14]
How do I createBlockchain for the publisher? Is there an example in the code and what information is needed?
Thank you very much and look forward to your answer！！！

**Comment by ghaemisr** [comment]
You can find an example publisher network under example-publisher. 
https://github.com/hyperledger-labs/pubsub-interop/tree/default/example-publisher/Fabric2

**Comment by EurusLiao** [comment]
> You can find an example publisher network under example-publisher.
> https://github.com/hyperledger-labs/pubsub-interop/tree/default/example-publisher/Fabric2

Thank you very much!!! I have solved this problem. 
But there are still some problems.
First, when I run createTopic on Publisher, why does app.post receive two identical requests on Broker?
Second, when I run publishToTopic on the publisher, and then the Broker sends an invoke message to Subscribe (Fabric1.4), MVCC_READ_CONFLICT ERROR will appear on Subscribe. I guess it is also because of the two post requests received on Broker. But I still don't know how to solve it. Looking forward to your answer! ! ! thank you very much! ! !
The following are some screenshots corresponding to these problems.
Problem1
<img width="913" alt="Problem1" src="https://user-images.githubusercontent.com/25023487/114590860-d7e72800-9cbb-11eb-9d4b-68802d18b6ee.png">
Problem2-1
<img width="1431" alt="Problem2-1" src="https://user-images.githubusercontent.com/25023487/114590890-de759f80-9cbb-11eb-95f9-b67a9721c0ec.png">
Problem2-2
<img width="1435" alt="Problem2-2" src="https://user-images.githubusercontent.com/25023487/114590903-e1709000-9cbb-11eb-951c-438c8b077076.png">

**Comment by ghaemisr** [comment]
The reason that two requests are received by the broker is that there are two peers on the publisher network and naturally they both run the smart contracts and send a request to the broker. That is what should be happening in the network. The broker will ignore all the requests after the first one by default. So the problem with your subscriber is not because of this. 
The MVCC_READ_CONFLICT ERROR could be because of your network setup. Try sending one request at a time and monitoring the request to see where the error originates from. 
I hope you find the problem!

**Comment by EurusLiao** [comment]
> The reason that two requests are received by the broker is that there are two peers on the publisher network and naturally they both run the smart contracts and send a request to the broker. That is what should be happening in the network. The broker will ignore all the requests after the first one by default. So the problem with your subscriber is not because of this.
> The MVCC_READ_CONFLICT ERROR could be because of your network setup. Try sending one request at a time and monitoring the request to see where the error originates from.
> I hope you find the problem!

Thanks for your answer!!!
I found the problem and I am trying to solve it.
